# Ensure WireGuard packages exists
- name: Install WireGuard dependencies
  apt:
    name:
      - wireguard
      - qrencode
    state: present
    update_cache: yes
    force: yes
  tags: install

# Ensure config folder exists
- name: Create WireGuard config and clients directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ wireguard.root }}/conf"
    - "{{ wireguard.root }}/conf/clients"

# Ensure IPv4 is enabled
- name: Ensure IPv4 forwarding is enabled persistently
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

# Validate peer names are unique
- name: Validate peer names
  import_tasks: validate-peers.yml

# Generate the server keys if not already generated
- name: Generate WireGuard keys
  import_tasks: server-keys.yml

# Generate peer keys if not already generated
- name: Configure WireGuard peers
  import_tasks: peers-keys.yml

- name: Configure WireGuard server interface
  import_tasks: server.yml
