# tasks/server-keys.yml

# Generate server keys
- name: Generate WireGuard private key (if missing)
  command: wg genkey
  register: wg_private
  args:
    creates: /{{ wireguard.root }}/conf/private.key

# Save private key if no key exists yet
- name: Save private key
  copy:
    content: "{{ wg_private.stdout }}"
    dest: /{{ wireguard.root }}/conf/private.key
    mode: '0600'
  when: wg_private is changed

# Generate public key
- name: Generate public key from private key
  shell: "wg pubkey < /{{ wireguard.root }}/conf/private.key"
  register: wg_public
  args:
    creates: "/{{ wireguard.root }}/conf/public.key"

# Save public key if no key exists yet
- name: Save public key
  copy:
    content: "{{ wg_public.stdout }}"
    dest: /{{ wireguard.root }}/conf/public.key
    mode: '0644'
  when: wg_public is changed

# Read the private key
- name: Read private key from remote host
  slurp:
    src: "{{ wireguard.root }}/conf/private.key"
  register: wg_private_key

- name: Set WireGuard private key variable
  set_fact:
    wg_private_key_content: "{{ wg_private_key.content | b64decode }}"
